### ISSUE TITLE
Generate .trc and .mot button generates only .c3d files in the project folder

### ISSUE THREAD

**Issue by frstrtr** [qualisys/paf-resources#5]
Generate .trc and .mot button generates only .c3d files in the project folder

log.txt:
Processing C:\paf-resources\OpenSim Example\Data\Jane Doe_0001\2021-02-17_CAST\Dynamic 1.c3d ... ERROR 
Processing C:\paf-resources\OpenSim Example\Data\Jane Doe_0001\2021-02-17_CAST\Dynamic 2.c3d ... ERROR 
Processing C:\paf-resources\OpenSim Example\Data\Jane Doe_0001\2021-02-17_CAST\Static 1.c3d ... ERROR 

possibly this happens if there is more than 1 python installed in the system, so the program aliases may help, but if python uses a launcher to start it may not...
"c:\py -3.7 ..." etc...
in this line of RunProcessing.php
https://github.com/qualisys/paf-resources/blob/3984181e9810ac0a66d76d7aa83699e5a71d8ca6/OpenSim%20Example/Templates/RunProcessing.php#L27

**Comment by DocVi** [comment]
Yes. Having multiple python instances on your computer can create the issue like yours. It is a known issue that we forgot to add in the Readme file. There is no perfect workaround unfortunately. We will try to use an alias for python and see if it helps.

**Comment by DocVi** [comment]
This issue is not related to this repo
